### ISSUE TITLE
Is there any property to differenciate this client from the "traditional" one?

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch-serverless-js#74]
I was wondering what would be the best way to differentiate this client and the _traditional_ one.
At the moment, I'm relying on `instanceof`, but that implies importing the class everywhere a typeguard is required.
Is there any property we can check to make the distinction?

Would the name help? As in setting it as `elasticsearch-serverless-js`?
https://github.com/elastic/elasticsearch-serverless-js/blob/67d185bf7eb4323b5ba9f914ef1077e1b06b7715/src/client.ts#L171

Although that seems configurable and maybe not 100% working solution.

**Comment by JoshMock** [comment]
This is a totally acceptable change. I'll open a PR shortly.
